AWSTemplateFormatVersion: "2010-09-09"
Description: "cfn-Add-RDS-Tokyo-Region. This template is not use in CloudFormation because of error occur. In actually, for has been created RDS Cross Region Read Replica using AWS Management Console.  "


Parameters:
  RDSMasterUserPassword:
    Type: String
    NoEcho: true
    Description: RDS Master User Password


Mappings:
  AccountToParam:
    # sea-dev
    "110636387318":
      MonitoringRoleArn: "arn:aws:iam::110636387318:role/rds-monitoring-role"
      CertificateArn: ""
    # dev-seapln-osr
    "716990209761":
      MonitoringRoleArn: "arn:aws:iam::716990209761:role/rds-monitoring-role"
      CertificateArn: "arn:aws:acm:ap-northeast-1:716990209761:certificate/35991408-f768-4680-9487-faed862441d7"
    # prod-seapln-osr
    "801004915087":
      MonitoringRoleArn: "arn:aws:iam::801004915087:role/rds-monitoring-role"
      CertificateArn: "arn:aws:acm:ap-northeast-1:801004915087:certificate/7a363c7d-2532-4acc-a82d-dfc1fa54d28e"

Resources:
#_____________________________________________________
#
#  RDS
#_____________________________________________________

  RDSDBCluster:
      Type: "AWS::RDS::DBCluster"
      Properties:
          AvailabilityZones: 
              - !Sub "${AWS::Region}a"
#              - !Sub "${AWS::Region}b"
              - !Sub "${AWS::Region}c"
          BackupRetentionPeriod: 1
          DatabaseName: "NAR_DB"
          DBClusterIdentifier: "nar-db-replication-tk-db"
          DBClusterParameterGroupName: "default.aurora5.6"
          DBSubnetGroupName: !Ref NarRDSDBSubnetGroup
          Engine: "aurora"
          Port: 3306
          MasterUsername: "narRoot"
          MasterUserPassword: !Ref RDSMasterUserPassword
          PreferredBackupWindow: "14:12-14:42"
          PreferredMaintenanceWindow: "fri:13:15-fri:13:45"

          # RDS Cross Region Read Replica
          ReplicationSourceIdentifier: !Sub "arn:aws:rds:eu-central-1:${AWS::AccountId}:cluster:nar-db"
          VpcSecurityGroupIds: 
            - !Ref NarSecurityGroupDB
          # KmsKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/9548c462-a47f-49a7-ae14-23792b4d68ee"
          StorageEncrypted: false
          EngineVersion: "5.6.mysql_aurora.1.22.2"
          EnableIAMDatabaseAuthentication: false
          EngineMode: "provisioned"
          DeletionProtection: true
#          EnableHttpEndpoint: false

  RDSDBInstance:
      Type: "AWS::RDS::DBInstance"
      Properties:
          DBInstanceIdentifier: "nar-db-replication-tk-db-ap-northeast-1a"
          DBInstanceClass: "db.r5.large"
          Engine: "aurora"
          DBName: "NAR_DB"
          PreferredBackupWindow: "14:12-14:42"
          AvailabilityZone: !Sub "${AWS::Region}a"
          PreferredMaintenanceWindow: "tue:20:26-tue:20:56"
          MultiAZ: false
          EngineVersion: "5.6.mysql_aurora.1.22.2"
          AutoMinorVersionUpgrade: true
          LicenseModel: "general-public-license"
          PubliclyAccessible: false
          StorageType: "aurora"
          Port: 3306
          DBClusterIdentifier: !Ref RDSDBCluster

          # Instances where StrageEncryoted is true, AWS KMS debt for encrypted DB files. True instance, kms year, apply signature, URL will be feedback. 
          # KmsKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/9548c462-a47f-49a7-ae14-23792b4d68ee"
          StorageEncrypted: false
          # Presigned_url: ""
          # SourceDBInstanceIdentifier: !Sub "arn:aws:rds:eu-central-1:${AWS::AccountId}:db:nar-db-instance"

          MonitoringInterval: 60
          PromotionTier: 1
          EnablePerformanceInsights: true

          # AWS KMS key identifier for performance insight data encryption. 
          PerformanceInsightsKMSKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/9548c462-a47f-49a7-ae14-23792b4d68ee"
          PerformanceInsightsRetentionPeriod: 7
          DBSubnetGroupName: !Ref NarRDSDBSubnetGroup
          VPCSecurityGroups: 
            - !Ref NarSecurityGroupDB
          DBParameterGroupName: "default.aurora5.6"
          OptionGroupName: "default:aurora-5-6"
          CACertificateIdentifier: "rds-ca-2019"

  RDSDBInstance2:
      Type: "AWS::RDS::DBInstance"
      Properties:
          DBInstanceIdentifier: "nar-db-replication-tk"
          DBInstanceClass: "db.r5.large"
          Engine: "aurora"
          DBName: "NAR_DB"
          PreferredBackupWindow: "14:12-14:42"
          AvailabilityZone: !Sub "${AWS::Region}c"
          PreferredMaintenanceWindow: "fri:13:11-fri:13:41"
          MultiAZ: false
          EngineVersion: "5.6.mysql_aurora.1.22.2"
          AutoMinorVersionUpgrade: true
          LicenseModel: "general-public-license"
          PubliclyAccessible: false
          StorageType: "aurora"
          Port: 3306
          DBClusterIdentifier: !Ref RDSDBCluster
          StorageEncrypted: false
          # KmsKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/9548c462-a47f-49a7-ae14-23792b4d68ee"
          # SourceDBInstanceIdentifier: !Sub "arn:aws:rds:eu-central-1:${AWS::AccountId}:db:nar-db-instance"
          MonitoringInterval: 60
          PromotionTier: 1
          EnablePerformanceInsights: true
          PerformanceInsightsKMSKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/9548c462-a47f-49a7-ae14-23792b4d68ee"
          PerformanceInsightsRetentionPeriod: 7
          DBSubnetGroupName: !Ref NarRDSDBSubnetGroup
          VPCSecurityGroups: 
            - !Ref NarSecurityGroupDB
          DBParameterGroupName: "default.aurora5.6"
          OptionGroupName: "default:aurora-5-6"
          CACertificateIdentifier: "rds-ca-2019"

  NarRDSDBSubnetGroup:
      Type: "AWS::RDS::DBSubnetGroup"
      Properties:
          DBSubnetGroupDescription: "NAR DB SUBNET GROUP"
          DBSubnetGroupName: "nar-db-subnet-gr"
          SubnetIds: 
            - !ImportValue ibaws-az-ibaws-system-vpc-Private0
            - !ImportValue ibaws-az-ibaws-system-vpc-Private1


# Custom Parameter Group (Cluster) 
  RDSDBClusterParameterGroup:
      Type: "AWS::RDS::DBClusterParameterGroup"
      Properties:
          Description: "custom-db-cluster-prmtgrp-aurora56"
          Family: "aurora5.6"
          Parameters: 
              binlog_format: "ROW"
              group_concat_max_len: "300000"

# Custom Parameter Group (Instance) 
  RDSDBParameterGroup:
      Type: "AWS::RDS::DBParameterGroup"
      Properties:
          Description: "custom-db-prmtgrp-aurora56"
          Family: "aurora5.6"





